### ISSUE TITLE
singularity: DrWatson not defined from ParameterRuns.jl

### ISSUE THREAD

**Issue by alee** [comses-education/spatialrust-model#4]
```
Singularity> julia scripts/ParameterRuns.jl
  Activating project at `/code`
ERROR: LoadError: UndefVarError: DrWatson not defined
Stacktrace:
 [1] parameters_experiment(conds::Dict{Symbol, Any})
   @ SpatialRust /code/src/Runners.jl:14
 [2] top-level scope
   @ /code/scripts/ParameterRuns.jl:41
in expression starting at /code/scripts/ParameterRuns.jl:41
Singularity> 
```

**Comment by manuvanegas** [comment]
Turns out I did need the DrWatson package for the parameter sweep 😅

**Comment by alee** [comment]
Thanks @manuvanegas ! That seems to have fixed the OSG runtime issue, and it's successfully run to completion and generated a parameterexp.csv file that I can send to you if you like. If you have any other test analyses you'd like to run, let me know! Happy to throw them at OSG and see if we can continue to improve the workflow.
