### ISSUE TITLE
Apptainer image seems to "forget" `instantiated` environment

### ISSUE THREAD

**Issue by manuvanegas** [comses-education/spatialrust-model#8]
The Apptainer action failed for ccc6557268ae90e8750446ee6122347c1107f175. The error message is saying that Julia can't find the first of the packages that were supposed to be added during the image build stage (specifically, during the `Pkg.instantiate()` call in `install.jl`). However the `instantiate` step seems to be working fine, according to the action's logs. It looks like, once the `build` step is finished, somehow the changes are not kept?

I am thinking this is an Apptainer-specific issue because the Docker action worked fine (see action executed for f400d6a28cd53b189aa43c931567d30e457b9f70).

**Comment by alee** [comment]
must be something we're missing with respect to how apptainer works

could take a look at other apptainer julia builds for inspiration

https://github.com/jaantollander/julia-apptainer

https://github.com/LCSB-BioCore/GigaSOM.jl/pkgs/container/apptainer%2Fgigasom.jl

**Comment by manuvanegas** [comment]
Fixed in b5f4d74ea95306d08cf94271e820505b15658eaf!
